### PR TITLE
Set custom gitlab instance url for authentication

### PR DESCRIPTION
**Pull request by jfreax**
Added new env variable "GITLAB_AUTH_URL"

### CODE REVIEW

**Comment by StephenOTT** [comment]
:no_mouth: That was a nice big oversight on my part!
Do you think this needs to be another env or can the GITLAB_ENDPOINT env be used?

Do people usually change their auth url in their own instance?

**Comment by jfreax** [comment]
I also thought about using GITLAB_ENDPOINT. But would you prefer to set GITLAB_ENDPOINT to something like "https://gitlab.com" or like it is know, the whole url including the api part (e.g. "https://gitlab.com/api/v3")

I mean, will this "/api/v3"-Endpoint ever change?

**Comment by StephenOTT** [comment]
Would prefer that the /api/v3 was editable when needed.  So how about we change ENDPOINT to your suggestion of just the base url.  We make a default value of /api/v3 unless overridden with another env such as endpoint_api_address

Thoughts?

**Comment by jfreax** [comment]
Sounds like a good idea :+1: 

I will change my PR accordingly.

**Comment by StephenOTT** [comment]
Looks good.

**Pull request merged**
